default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: realvtuber_development
  host: localhost
  username: root
  password: "<%= Rails.application.credentials.local_db_pass %>"

test:
  <<: *default
  database: realvtuber_test
  host: localhost
  username: root
  password: "<%= Rails.application.credentials.local_db_pass %>"

production:
  <<: *default
  url: "<%= Rails.application.credentials.cleardb_database_url %>"
