default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: realvtuber_development

test:
  <<: *default
  database: realvtuber_test

production:
  <<: *default
  url: ""
