default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: realvtuber_development
  host: localhost
  username: root
  password:

test:
  <<: *default
  database: realvtuber_test
  host: localhost
  username: root
  password:

production:
  <<: *default
  url: <%= Rails.application.credentials.cleardb_database_url %>
